version: "3.9"

services:
  signers-db:
    image: postgres:15.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_PORT:-5432}:5432

  signers-back:
    build: ./signers-back
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=${PORT:-3000}
    volumes:
      - ./signers-back:/app

  signers-front:
    build: ./signers-front
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - signers-back
    networks:
      - signers-front-net

  nginx:
    image: nginx:latest
    ports:
      - "${PORT:-8080}:80"
    volumes:
      - ./signers-front/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - signers-front
      - signers-back
    networks:
      - signers-front-net

networks:
  signers-front-net:
    driver: bridge
