version: "3.9"

services:
  signers-back:
    build: ./signers-back
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=${PORT:-3000}

  signers-front:
    build: ./signers-front
    ports:
      - "${PORT:-80}:80"
    depends_on:
      - signers-back
