version: "3.9"

services:
  signers-back:
    build: ./signers-back  # Path to the back-end service directory
    ports:
      - "${PORT:-3000}:3000"  # Map back-end port (example)
    environment:
      - PORT=${PORT:-3000}

  signers-front:
    build: ./signers-front  # Path to the front-end service directory
    ports:
      - "${PORT:-80}:80"  # Map front-end port (example)
    depends_on:
      - signers-back  # Front-end depends on back-end being up first
