version: "3.9"

services:
  signers-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./signers-db:/var/lib/postgresql/data

  signers-back:
    build:
      context: ./signers-back
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=${PORT:-3000}
    volumes:
      - ./signers-back:/nestapp
    command: pnpm start:dev

  signers-front:
    build:
      context: ./signers-front
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT:-5173}:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./signers-front:/vueapp
    command: pnpm dev

volumes:
  signers-db:
