version: "3.9"

services:
  signers-back:
    build: ./signers-back
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=${PORT:-3000}
    volumes:
      - ./signers-back:/app

  signers-front:
    build: ./signers-front
    ports:
      - "${PORT:-5173}:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - signers-back
