# Use node image for building and nestjs image for final stage
FROM node:21-alpine As builder

RUN npm install -g pnpm

# Create app directory
WORKDIR /nestapp

# Copy package.json
COPY package*.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install --frozen-lockfile

COPY . .

# EXPOSE ${PORT:-3000}

# CMD ["pnpm", "start:dev"]
